# Camera Configuration for RealSense D435
camera:
  type: "RealSense D435"
  streams:
    color:
      width: 640
      height: 480
      format: "bgr8"
      fps: 30
    depth:
      width: 640
      height: 480
      format: "z16"
      fps: 30
  
  # Camera offset from robot flange (meters)
  offset:
    x: 0.0
    y: 0.0
    z: 0.0225  # 22.5mm

# Object Detection Settings
detection:
  method: "april_tags"
  tag_family: "tagStandard41h12"
  tag_size_mm: 100.0
  confidence_threshold: 0.8
  max_objects: 10
  
# Object ID Mapping
object_mapping:
  0: "bottle"
  1: "book"
  2: "cup"
  3: "pen"
  4: "phone"
  5: "laptop"
  6: "notebook"
  7: "stapler"
  8: "keyboard"
  9: "mouse"
  10: "calculator"
  
# Vision Processing
processing:
  enable_depth_filtering: true
  min_depth: 0.1  # meters
  max_depth: 2.0  # meters
  enable_pose_estimation: true 