# April Tags Detection Configuration

april_tags_detector:
  ros__parameters:
    # Tag detection parameters
    tag_size_mm: 100.0                   # Physical size of April Tags in millimeters (100mm for desk objects)
    confidence_threshold: 0.8            # Minimum confidence for detection (0.0-1.0)
    
    # Frame IDs
    camera_frame_id: "camera_link"       # Camera frame ID
    robot_frame_id: "base_link"          # Robot base frame ID
    
    # Publishing settings
    publish_rate: 10.0                    # Publishing rate in Hz
    enable_3d_pose: true                 # Enable 3D pose estimation
    enable_robot_coords: true            # Enable robot coordinate transformation
    show_debug_image: true               # Show debug image with detections
    
    # Object mapping
    object_mapping:
      0: "bottle"
      1: "book"
      2: "cup"
      3: "pen"
      4: "phone"
      5: "laptop"
      6: "notebook"
      7: "stapler"
      8: "keyboard"
      9: "mouse"
      10: "calculator"
    
    # Camera settings
    camera:
      width: 640
      height: 480
      fps: 30
      color_format: "bgr8"
      depth_format: "z16"
    
    # Processing settings
    processing:
      enable_depth_filtering: true
      min_depth: 0.1  # meters
      max_depth: 2.0  # meters
      enable_pose_estimation: true
